  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: devops-workflow-deployment
    labels:
      app: devops-workflow
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: devops-workflow
    template:
      metadata:
        labels:
          app: devops-workflow
      spec:
        containers:
        - name: moscow-time
          image: marko453/devops:latest
          ports:
          - containerPort: 8000


